version: '3.0'

services:
  ### MySQL ##########################################
  database:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command:
      mysqld --sql_mode='' --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - '127.0.0.1:${DB_PORT}:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  ### PHP ##########################################
  php:
    container_name: php-container
    restart: always
    build:
      context: ./php
    env_file:
      - .env
    ports:
      - '127.0.0.1:${PHP_PORT}:9000'
    volumes:
      - ./www/app:/var/www/app
      - ./php/xdebug.ini:/usr/local/etc/php/docker-php-ext-xdebug.ini
      - ./php/error_reporting.ini:/usr/local/etc/php/error_reporting.ini
    depends_on:
      - database

  ### NGINX server ##########################################
  nginx:
    container_name: nginx-container
    restart: always
    image: nginx:stable-alpine
    ports:
      - '${NGINX_HTTP_PORT}:80'
    volumes:
      - ./www/app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
